// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Back5: typeof import('./components/Back5.vue')['default']
    ClearLoops: typeof import('./components/ClearLoops.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    CurrentLoop: typeof import('./components/CurrentLoop.vue')['default']
    CustomControlGroup: typeof import('./components/CustomControlGroup.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Forward5: typeof import('./components/Forward5.vue')['default']
    List: typeof import('./components/list.vue')['default']
    ListView: typeof import('./components/ListView.vue')['default']
    LoopButton: typeof import('./components/LoopButton.vue')['default']
    LoopControl: typeof import('./components/LoopControl.vue')['default']
    LoopEndold: typeof import('./components/LoopEndold.vue')['default']
    LoopStart: typeof import('./components/LoopStart.vue')['default']
    PlayerUI: typeof import('./components/PlayerUI.vue')['default']
    README: typeof import('./components/README.md')['default']
    RestartControl: typeof import('./components/RestartControl.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./components/Test.vue')['default']
    VideoPlayer: typeof import('./components/VideoPlayer.vue')['default']
    VidStackPlayer: typeof import('./components/VidStackPlayer.vue')['default']
    VimePlayer: typeof import('./components/VimePlayer.vue')['default']
  }
}
